import { defineConfig } from "@terrazzo/cli";
import vscodeTheme from "./plugins/vscode-theme.mjs";

export default defineConfig({
  tokens: [
    "./tokens/core.tokens.json",
    "./tokens/dark/background.tokens.json",
    "./tokens/dark/border.tokens.json",
    "./tokens/dark/font.tokens.json",
    "./tokens/application/activityBar.tokens.json",
    "./tokens/application/badge.tokens.json",
    "./tokens/application/base.tokens.json",
    "./tokens/application/bracketPairs.tokens.json",
    "./tokens/application/breadcrumb.tokens.json",
    "./tokens/application/button.tokens.json",
    "./tokens/application/contrast.tokens.json",
    "./tokens/application/debug.tokens.json",
    "./tokens/application/diffEditor.tokens.json",
    "./tokens/application/dropdown.tokens.json",
    "./tokens/application/editor.tokens.json",
    "./tokens/application/editorGroup.tokens.json",
    "./tokens/application/editorWidget.tokens.json",
    "./tokens/application/extension.tokens.json",
    "./tokens/application/git.tokens.json",
    "./tokens/application/input.tokens.json",
    "./tokens/application/list.tokens.json",
    "./tokens/application/menu.tokens.json",
    "./tokens/application/merge.tokens.json",
    "./tokens/application/minimap.tokens.json",
    "./tokens/application/notication.tokens.json",
    "./tokens/application/panel.tokens.json",
    "./tokens/application/peekView.tokens.json",
    "./tokens/application/progressBar.tokens.json",
    "./tokens/application/quickPicker.tokens.json",
    "./tokens/application/scrollbar.tokens.json",
    "./tokens/application/settings.tokens.json",
    "./tokens/application/sideBar.tokens.json",
    "./tokens/application/statusBar.tokens.json",
    "./tokens/application/tab.tokens.json",
    "./tokens/application/terminal.tokens.json",
    "./tokens/application/text.tokens.json",
    "./tokens/application/titleBar.tokens.json",
    "./tokens/application/welcomePage.tokens.json",
    "./tokens/syntax/comment.tokens.json",
    "./tokens/syntax/constant.tokens.json",
    "./tokens/syntax/entity.tokens.json",
    "./tokens/syntax/invalid.tokens.json",
    "./tokens/syntax/json.tokens.json",
    "./tokens/syntax/keyword.tokens.json",
    "./tokens/syntax/markup.tokens.json",
    "./tokens/syntax/meta.tokens.json",
    "./tokens/syntax/punctuation.tokens.json",
    "./tokens/syntax/storage.tokens.json",
    "./tokens/syntax/string.tokens.json",
    "./tokens/syntax/support.tokens.json",
    "./tokens/syntax/variable.tokens.json",
  ],
  outDir: "./themes/",
  plugins: [
    vscodeTheme({
      name: "Little League",
      modes: ["dark"],
      variant: "er",
    }),
  ],
});
