id = "little-league-theme"
name = "Little League"
version = "1.5.1"
schema_version = 1
description = "A quiet theme with harmonious colors"
authors = ["Matt Strom <https://github.com/ilikescience>"]
repository = "https://github.com/ilikescience/little-league"
